pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh """
                    rm -rf build
                    mkdir build
                    cd build
                    cmake ..
                    make
                    ../debian/make-deb-pkg.sh \$(cat ../VERSION.txt)
                """
                archiveArtifacts 'build/*.deb'
            }
        }
    }
}
